#!/usr/bin/perl -w
# Copyright (C) 2012 Intel Corporation
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

use FindBin;
use lib $FindBin::Bin;
use webkitdirs;

my $scriptsDir = relativeScriptsDir();
system("perl", "$scriptsDir/update-webkit-libs-jhbuild", "--sling", @ARGV) == 0 or die $!;

my $checkoutRoot = File::Spec->catdir(baseProductDir(), "DependenciesSLING", "Source");
my $sdkPath = File::Spec->catdir($checkoutRoot, "android-sdk");
my $sdkToolsPath = File::Spec->catdir($checkoutRoot, "android-sdk-tools");

if(! -d "$sdkPath/platforms/android-19") {
    system("cp", "-rf", "$sdkToolsPath/platforms", $sdkPath);
}
if(! -d "$sdkPath/platform-tools") {
    system("cp", "-rf", "$sdkToolsPath/platform-tools", $sdkPath);
}
if(! -d "$sdkPath/build-tools/19.0.1") {
    system("cp", "-rf", "$sdkToolsPath/build-tools", $sdkPath);
}
